DROP TABLE IF EXISTS `task`;
CREATE TABLE `task` (
  `task_id` int(11) NOT NULL auto_increment,
  `url` varchar(255) default NULL,
  `encounter_type` varchar(255) default NULL,
  `description` text default NULL,
  `location` varchar(255) default NULL,
  `gender` varchar(50) default NULL,
  `has_obs_concept_id` int(11) default NULL,
  `has_obs_value_coded` int(11) default NULL,
  `has_obs_value_drug` int(11) default NULL,
  `has_obs_value_datetime` datetime default NULL,
  `has_obs_value_numeric` double default NULL,
  `has_obs_value_text` text default NULL,
  `has_program_id` int(11) default NULL,
  `has_program_workflow_state_id` int(11) default NULL,
  `has_identifier_type_id` int(11) default NULL,
  `has_relationship_type_id` int(11) default NULL,
  `has_order_type_id` int(11) default NULL,
  `sort_weight` double default NULL,
  `creator` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `voided` smallint(6) default 0,
  `voided_by` int(11) default NULL,
  `date_voided` datetime default NULL,
  `void_reason` varchar(255) default NULL,
  `changed_by` int(11) default NULL,
  `date_changed` datetime default NULL,
  `uuid` char(38) default NULL,
  PRIMARY KEY  (`task_id`),
  KEY `task_creator` (`creator`),
  KEY `user_who_voided_task` (`voided_by`),
  KEY `user_who_changed_task` (`changed_by`),
  CONSTRAINT `task_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `user_who_changed_task` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `user_who_voided_task` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17450 DEFAULT CHARSET=utf8;

