# production:
#   adapter: mysql
#   database: openmrs
#   username: root
#   password:
#   host: localhost

development:
  adapter: mysql
  database: mnch_development
  username: root
  password: ben979
  host: localhost

test: &TEST
  adapter: mysql
  database: bart2_test
  username: root
  password: ben979
  host: localhost

cucumber:
  <<: *TEST
