Feature: Register A Client
As a user
I would like to register a client


	Scenario: Client register a client successifully
		Given I am on the "Register A Client" page
		Then I should see "First name"
		Then I fill in "First name" with "Tisunge"
		Then I should see "Last name"
		Then I fill in "Last name" with "Milimbo"
		Then I should see "Gender"
		And I should see ""
		And I should see "Male"
		And I should see "Female"
		And I select "Female"
		Then I should see "Year of birth"
		Then I fill in "Year of birth" with ""
		Then I should see "Month"
		And I should see ""
		And I should see "Jan"
    And I should see "Feb"
    And I should see "Mar"
    And I should see "Apr"
    And I should see "May"
    And I should see "Jun"
    And I should see "Jul"
    And I should see "Aug"
    And I should see "Sep"
    And I should see "Oct"
    And I should see "Nov"
    And I should see "Dec"
    And I should see "Unknown"
		And I select "Jan"
		Then I should see "Day"
		Then I fill in "Day" with ""
		Then I should see "Age Estimate" If "Year of birth" != ""
		Then I fill in "Age Estimate" with ""
		Then I should see "Home Village"
		Then I fill in "Home Village" with ""
		Then I should see "Current Traditional Authority (TA)"
		Then I fill in "Current Traditional Authority (TA)" with ""
		Then I should see "Current Village"
		Then I fill in "Current Village" with ""
		Then I should see "Cell Phone Number"
		Then I fill in "Cell Phone Number" with ""
		Then I should see "Occupation"
		Then I fill in "Occupation" with ""
		And I press "Finish"
		Then I should be on the next page
